export default {  
   "skuId":"7332059",
   "active":true,
   "attributes":{  
      "lowPriceGuaranteedProduct":true,
      "onlineOnly":true
   },
   "availability":{  
      "pickup":{  
         "available":true,
         "availabilityCode":"115",
         "checkStoresLink":{  
            "url":"/site/olstemplatemapper.jsp?id=pcat17006&type=page&sourceId=1122653022021&sourceType=product&skuId=7332059&productId=1122653022021&pageMode=searchmode"
         },
         "displayMessage":"<b>Store Pickup:</b>"
      },
      "ship":{  
         "available":true,
         "checkLink":{  
            "height":470,
            "target":"popup",
            "url":"/site/olspage.jsp?id=cat13503&type=page&skuId=7332059",
            "width":530
         },
         "displayMessage":"<b>Shipping:</b>  Usually leaves our warehouse in 1 business day",
         "getItBy":{  
            "currentPrice":28.99,
            "availabilityCode":"110",
            "regionalAvailabilityEligible":true
         }
      }
   },
   "brand":{  
      "brand":"Microsoft"
   },
   "class":{  
      "displayName":"INPUT DEVICES",
      "id":"158"
   },
   "condition":"new",
   "customerRatings":{  
      "averageFeatureRating":[  
         {  
            "displayName":"Value for Price",
            "percent0To1":0.86,
            "percent0To100":86,
            "rangeMax":5,
            "score":4.3
         },
         {  
            "displayName":"Compatibility",
            "percent0To1":0.92,
            "percent0To100":92,
            "rangeMax":5,
            "score":4.6
         },
         {  
            "displayName":"Design",
            "percent0To1":0.88,
            "percent0To100":88,
            "rangeMax":5,
            "score":4.4
         },
         {  
            "displayName":"Ease of Use",
            "percent0To1":0.88,
            "percent0To100":88,
            "rangeMax":5,
            "score":4.4
         }
      ],
      "averageRating":{  
         "percent0To1":0.9,
         "percent0To100":90,
         "rangeMax":5,
         "score":4.5
      },
      "averageWouldRecommend":{  
         "percent0To1":0.92,
         "percent0To100":92,
         "totalCount":756
      },
      "mdotUrl":"/m/e/product/reviews.jsp?skuId=7332059&pid=1122653022021&sr=01",
      "starRatingBreakdown":[  
         {  
            "count":553,
            "percent0To100":68,
            "score":5
         },
         {  
            "count":199,
            "percent0To100":24,
            "score":4
         },
         {  
            "count":35,
            "percent0To100":4,
            "score":3
         },
         {  
            "count":19,
            "percent0To100":2,
            "score":2
         },
         {  
            "count":19,
            "percent0To100":2,
            "score":1
         }
      ],
      "totalCount":825
   },
   "department":{  
      "displayName":"COMPUTERS",
      "id":"6"
   },
   "descriptions":{  
      "short":"For PC and Mac; natural wrist alignment; Intuitive Zoom Slider; 1-touch functionality; improved number pad"
   },
   "itemId":"890878",
   "manufacturerId":{  
      "modelNumber":"B2M-00012"
   },
   "mdotBuyingOptionsUrl":"/m/e/product/morebuyingoptions.jsp?checkForPlansAndAccessories=true&skuId=7332059&productId=1122653022021",
   "media":{  
      "primaryImage":{  
         "aspectRatio":1.7986,
         "height":278,
         "path":"BestBuy_US/images/products/7332/7332059_sa.jpg",
         "url":"http://img.bbystatic.com/BestBuy_US/images/products/7332/7332059_sa.jpg",
         "altText":"Microsoft - Natural Ergonomic Keyboard 4000 - Black - Larger Front",
         "width":500
      },
      "listImage":{  
         "aspectRatio":1.8103,
         "height":58,
         "path":"BestBuy_US/images/products/7332/7332059_sc.jpg",
         "url":"http://img.bbystatic.com/BestBuy_US/images/products/7332/7332059_sc.jpg",
         "altText":"Microsoft - Natural Ergonomic Keyboard 4000 - Black",
         "width":105
      },
      "thumbnailImage":{  
         "aspectRatio":1.6364,
         "height":33,
         "path":"BestBuy_US/images/products/7332/7332059_s.gif",
         "url":"http://img.bbystatic.com/BestBuy_US/images/products/7332/7332059_s.gif",
         "altText":"Microsoft - Natural Ergonomic Keyboard 4000 - Black",
         "width":54
      }
   },
   "meta":{  
      "description":"MICROSOFT Ergonomic Keyboard: For PC and Mac; natural wrist alignment; Intuitive Zoom Slider; 1-touch functionality; improved number pad",
      "keywords":"MICROSOFT, Ergonomic Keyboard, B2M-00012, Keyboards, Computer Accessories",
      "title":"Microsoft Natural Ergonomic Keyboard 4000 Black B2M-00012"
   },
   "names":{  
      "short":"Microsoft - Natural Ergonomic Keyboard 4000 - Black"
   },
   "parentCategory":{  
      "displayName":"Wired & USB Keyboards",
      "categoryId":"pcmcat338200050012"
   },
   "productId":"1122653022021",
   "productType":"hardgood",
   "properties":{  
      "format":"physical",
      "freeShippingCode":"freeShipping"
   },
   "specialOffers":[  
      {  
         "height":600,
         "type":"Shipping Global",
         "startDate":"2015-09-22T05:00Z",
         "name":"Free Shipping",
         "target":"popup",
         "url":"/site/offer/127051/pcmcat748300476483.c?id=pcmcat748300476483",
         "width":860,
         "displayOnMdot":true,
         "checkMarkMessagingPriority":"High",
         "priority":"8"
      }
   ],
   "subclass":{  
      "displayName":"KEYBOARDS",
      "id":"597"
   },
   "url":"/site/microsoft-natural-ergonomic-keyboard-4000-black/7332059.p?id=1122653022021&skuId=7332059"
}
